### ISSUE TITLE
Does okteto stacks support autoscaling somehow? 

### ISSUE THREAD

**Issue by liflovs** [okteto/stacks#9]

**Comment by pchico83** [comment]
Okteto Stacks run on Kubernetes, you can configure your HPA in Kubernetes

**Comment by liflovs** [comment]
@pchico83  Thanks, Im just worrying wont be any conflict or similar? Lets say in my docker compose I have 2 replicas stated, wont this be enforced, etc.

**Comment by pchico83** [comment]
@liflovs yes, we support `replicas` and `scale` in the compose file:
https://okteto.com/docs/reference/stacks/#scale-int-optional
